// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-Kc9k7UkqtP7qtlsFldRq6rGhRQiJ78',
    appId: '1:720806980725:web:c89408c993d8c6382cdc3c',
    messagingSenderId: '720806980725',
    projectId: 'flutterchat-70fbc',
    authDomain: 'flutterchat-70fbc.firebaseapp.com',
    storageBucket: 'flutterchat-70fbc.appspot.com',
    measurementId: 'G-GN128PRXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa28LTWY9QxpwexGDpB1vCiYytxN6A9yM',
    appId: '1:720806980725:android:17c5d6609476ace12cdc3c',
    messagingSenderId: '720806980725',
    projectId: 'flutterchat-70fbc',
    storageBucket: 'flutterchat-70fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZmbTe7By5DDwT0XLTN_vXkDsSDm9CRQ',
    appId: '1:720806980725:ios:687461ea2dcaf4d62cdc3c',
    messagingSenderId: '720806980725',
    projectId: 'flutterchat-70fbc',
    storageBucket: 'flutterchat-70fbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
